// Shared blog post data used by both the listing page and individual article pages

export const authors = {
    aisha: { name: "Dr. Aisha Patel", role: "Head of AI Research", initials: "AP", color: "from-indigo-500 to-purple-600", bio: "PhD in ML from Stanford. Previously researched language model personalization at Google DeepMind.", articles: 14 },
    carlos: { name: "Carlos Ruiz", role: "Deliverability Engineer", initials: "CR", color: "from-emerald-500 to-teal-600", bio: "8 years hardening email infrastructure at ISPs. Obsessed with inbox placement rates.", articles: 9 },
    sophie: { name: "Sophie Laurent", role: "Growth Strategist", initials: "SL", color: "from-amber-500 to-orange-600", bio: "Ran lifecycle email at three SaaS unicorns before joining MailMind's strategy team.", articles: 11 },
    marcus: { name: "Marcus Webb", role: "Data Science Lead", initials: "MW", color: "from-sky-500 to-blue-600", bio: "Turned 2.3 billion send events into our predictive engagement engine. Numbers are his love language.", articles: 7 },
    tyler: { name: "Tyler Brooks", role: "Campaign Strategist", initials: "TB", color: "from-teal-500 to-emerald-600", bio: "Built and scaled email programs at B2C brands with up to 12M subscribers.", articles: 8 },
    leo: { name: "Leo Nakamura", role: "Product & Analytics", initials: "LN", color: "from-violet-500 to-purple-600", bio: "Ships features by day, analyzes send-time data by night. Core architect of MailMind's reporting layer.", articles: 6 },
    legal: { name: "MailMind Legal Team", role: "Compliance & Trust", initials: "ML", color: "from-rose-500 to-pink-600", bio: "Our in-house data protection officers and compliance analysts.", articles: 5 },
} as const

export type AuthorKey = keyof typeof authors

export interface BlogPost {
    id: string
    category: string
    readTime: string
    date: string
    featured: boolean
    title: string
    subtitle: string
    excerpt: string
    body: string[]
    authorKey: AuthorKey
    tags: string[]
    color: string
    views: string
    likes: string
}

export const posts: BlogPost[] = [
    {
        id: "end-of-generic-email",
        category: "AI & Automation",
        readTime: "8 min",
        date: "Feb 18, 2026",
        featured: true,
        title: "The End of Generic Email: How Predictive AI Is Rewriting Personalization",
        subtitle: "Mass-blast email is dead. Open rates are never going back.",
        excerpt: "Mass-blast email is dead. Learn how next-gen AI models are crafting individually resonant messages at scale — and why open rates are never going back.",
        body: [
            "For two decades, email marketing operated on a simple, brutal assumption: send the same message to everyone and hope that a sliver of your list cares. The average open rate hovered between 18–22% across industries and marketers called it a success.",
            "In 2026, that's no longer acceptable — and it's no longer necessary. Predictive personalization models can now analyze each subscriber's behavioral fingerprint: what they open, when they open it, what they click, how long they linger, what they ignore. From that signal, AI crafts subject lines, preview text, and body copy that feel as though they were written for one person.",
            "The results aren't incremental. Customers using MailMind's personalization engine see, on average, a 312% lift in open rates versus their pre-AI baseline. One e-commerce customer went from 12% to 68% open rates in under 30 days.",
            "The mechanism is surprisingly intuitive once you understand it: humans respond to content that reflects their reality. A subject line that references the specific product you browsed last Tuesday, arriving on a Wednesday at 10:14am because that's when you historically open your inbox — that's not email marketing anymore. That's relevance.",
            "The most important shift isn't technical — it's conceptual. Stop thinking about your list as an audience and start thinking about it as 100,000 individual relationships, each with its own cadence, vocabulary, and emotional state. AI makes that possible. The only thing holding most teams back is the mental model, not the tool.",
            "Early adopters of predictive personalization are already pulling so far ahead of the competitive field that the gap may become insurmountable within two years. The question for every email marketer today isn't whether to adopt AI personalization — it's whether you can afford to wait.",
        ],
        authorKey: "aisha",
        tags: ["AI", "Personalization", "Open Rates", "LLM"],
        color: "from-indigo-500 to-purple-600",
        views: "12.4K",
        likes: "847",
    },
    {
        id: "spf-dkim-dmarc-2026",
        category: "Deliverability",
        readTime: "5 min",
        date: "Feb 15, 2026",
        featured: false,
        title: "SPF, DKIM, DMARC: A No-BS Guide for 2026",
        subtitle: "Authentication protocols are your first line of defense against spam folders.",
        excerpt: "Authentication protocols are your first line of defense against spam folders. Here's what actually matters and a step-by-step setup walkthrough.",
        body: [
            "If your emails are landing in spam, there's a 70% chance it's a DNS configuration problem. SPF, DKIM, and DMARC aren't optional extras — they're the foundation of inbox placement in 2026.",
            "SPF (Sender Policy Framework) tells receiving servers which IP addresses are authorized to send email on behalf of your domain. Set it up by adding a TXT record to your DNS: `v=spf1 include:sendgrid.net ~all`. The `~all` is a soft fail — it flags unauthorized senders but doesn't reject them. Use `-all` once you're confident your SPF record is complete.",
            "DKIM (DomainKeys Identified Mail) cryptographically signs each message using a private key you hold, and publishes the corresponding public key in your DNS. Receiving servers verify the signature to confirm the message wasn't tampered with in transit. Every reputable ESP gives you DKIM keys to add to your DNS — just follow their guide and verify with a tool like MXToolbox.",
            "DMARC (Domain-based Message Authentication, Reporting & Conformance) tells receiving servers what to do when SPF or DKIM checks fail. The most common mistake? Setting DMARC to `p=none` and forgetting about it. That tells receiving servers to do nothing when authentication fails — effectively defeating the entire point.",
            "The correct progression: start with `p=none; rua=mailto:dmarc@yourdomain.com` to collect reports without affecting deliverability. After two weeks of monitoring, move to `p=quarantine` (sends failures to spam). After another two weeks with clean reports, move to `p=reject` (blocks unauthenticated senders entirely). This is the gold standard.",
            "Finally, set up BIMI (Brand Indicators for Message Identification) if you want your logo to appear next to your emails in Gmail and Apple Mail. It requires a verified Mark Certificate (VMC) and a published `p=reject` DMARC policy. It's the finishing touch that signals enterprise-grade seriousness to both ISPs and subscribers.",
        ],
        authorKey: "carlos",
        tags: ["Deliverability", "DNS", "SPF", "DKIM", "DMARC"],
        color: "from-emerald-500 to-teal-600",
        views: "8.1K",
        likes: "512",
    },
    {
        id: "behavioral-triggers",
        category: "Strategy",
        readTime: "6 min",
        date: "Feb 12, 2026",
        featured: false,
        title: "Behavioral Triggers: The Campaign Type That Outperforms Everything",
        subtitle: "Behavior-driven campaigns consistently beat scheduled blasts by 3–5×.",
        excerpt: "Campaigns driven by real-time user behavior consistently beat scheduled blasts by 3–5×. Here's the blueprint for building a behavioral email engine.",
        body: [
            "The highest-performing email campaigns in MailMind's platform aren't the ones with the most beautiful design or the cleverest subject lines. They're the ones triggered by real user behavior at the exact moment of relevance.",
            "Behavioral triggers include: first product view, cart abandonment, feature activation, pricing page visit, re-engagement windows, and milestone completions. Each of these represents a moment when the subscriber's intent is measurable — and actionable.",
            "The key is specificity. An email that fires 47 minutes after a cart is abandoned, with a subject line referencing the specific item left behind, outperforms a 24-hour generic cart recovery email by an average of 4.2× in click-to-purchase rate across our customer base.",
            "Building a behavioral email engine starts with instrumentation. You need events flowing from your product or website to your email platform in real time. MailMind's webhook system accepts events in any format and maps them to triggers within minutes — no engineering sprint required.",
            "The second step is defining your trigger logic. For each behavioral event, decide: what's the ideal delay (immediate, 30 min, 2 hours, 24 hours)? What's the suppression rule (don't send if they've already purchased)? What's the exit condition (stop the sequence if they convert)?",
            "Finally, personalize within the trigger. A cart abandonment email is table stakes. A cart abandonment email that references the specific item, the last three products they viewed, and the discount tier they qualify for — that's what separates a 2% recovery rate from a 9% one.",
        ],
        authorKey: "sophie",
        tags: ["Automation", "Triggers", "Lifecycle", "Behavioral"],
        color: "from-amber-500 to-orange-600",
        views: "6.8K",
        likes: "431",
    },
    {
        id: "metrics-that-predict-revenue",
        category: "Analytics",
        readTime: "7 min",
        date: "Feb 9, 2026",
        featured: false,
        title: "Beyond Open Rate: The 7 Metrics That Actually Predict Email Revenue",
        subtitle: "Revenue-per-subscriber is what elite email teams track instead.",
        excerpt: "Open rates are vanity. Revenue-per-subscriber, engagement decay curves, and send-time elasticity are what elite email teams track instead.",
        body: [
            "Open rate is the metric that email marketers learned to report on because it was the first thing ESPs made easy to see. It's also one of the least predictive signals for actual business outcomes — especially since Apple's Mail Privacy Protection introduced phantom opens in 2021.",
            "The seven metrics that actually correlate with email-attributed revenue are: Revenue Per Subscriber (RPS), Engagement Decay Rate, Send-Time Elasticity, List Health Score, Click Depth Index, Re-engagement Response Rate, and Churn Prediction Signal.",
            "Revenue Per Subscriber is the North Star. A list of 10,000 engaged subscribers generating $4.50 RPS will always outperform a list of 100,000 with a $0.12 RPS. The goal isn't a big list — it's a valuable one. Calculate it monthly: total email-attributed revenue ÷ total active subscribers.",
            "Engagement Decay Rate measures how quickly a subscriber's engagement drops off after joining. A healthy list shows a decay curve that flattens after week four as engaged subscribers stabilize. A list with ongoing decay means your onboarding sequence isn't establishing the habit.",
            "Send-Time Elasticity tells you how sensitive your audience's open rate is to changes in send time. A high-elasticity audience (early-stage B2B buyers) responds dramatically differently to Tuesday vs. Thursday sends. Low-elasticity audiences (daily newsletter readers) barely notice. Knowing your elasticity tells you how much time to invest in send-time optimization.",
            "The remaining three — List Health Score, Click Depth Index, and Churn Prediction Signal — are leading indicators. They tell you what your revenue will look like in 90 days, not what it looked like last month. MailMind's dashboard surfaces all seven automatically so you can catch problems before they show up in revenue.",
        ],
        authorKey: "marcus",
        tags: ["Analytics", "Metrics", "Revenue", "Data"],
        color: "from-sky-500 to-blue-600",
        views: "9.3K",
        likes: "604",
    },
    {
        id: "llm-copy-at-scale",
        category: "AI & Automation",
        readTime: "9 min",
        date: "Feb 6, 2026",
        featured: false,
        title: "LLM-Generated Copy at Scale: Quality Controls That Work",
        subtitle: "Generating thousands of variants with AI — but only if you have guardrails.",
        excerpt: "Generating thousands of personalized email variants with AI is powerful — but only if you have guardrails. We share our internal review framework.",
        body: [
            "When we first deployed LLM-generated email copy for customers at scale, we immediately discovered the problem that anyone working with language models knows well: the model is confident even when it's wrong, and at high volume, hallucinations compound.",
            "Our quality control framework consists of five layers: brand voice scoring, fact-checking, compliance screening, human-in-the-loop review, and A/B performance gates.",
            "Brand voice scoring uses embedding similarity to compare generated copy against a corpus of approved, high-performing copy from that customer. Variants that score below a cosine similarity threshold of 0.78 are automatically regenerated with tighter constraints.",
            "Fact-checking runs the generated copy against the customer's product data API. If the copy references a price, a feature name, or a date, the system verifies it exists and is current before the message is queued. This layer alone catches approximately 3% of all generations in production.",
            "Compliance screening flags copy containing prohibited phrases under GDPR, CAN-SPAM, and customer-specific brand guidelines. The flagged content is routed to a human reviewer rather than regenerated — some flags are intentional edge cases that a human should make a judgment call on.",
            "The A/B performance gate is the most powerful control. Every generated variant starts at zero confidence. As it accumulates opens and clicks, its confidence score rises. Variants with strong early signal are automatically scaled to more recipients. Underperformers are retired. The result: our AI-generated copy now outperforms human-written benchmarks in 71% of A/B tests.",
        ],
        authorKey: "aisha",
        tags: ["AI", "LLM", "Copywriting", "Quality"],
        color: "from-violet-500 to-indigo-600",
        views: "7.2K",
        likes: "489",
    },
    {
        id: "gdpr-2026",
        category: "Compliance",
        readTime: "4 min",
        date: "Feb 3, 2026",
        featured: false,
        title: "GDPR in 2026: What's Changed and What Email Marketers Must Do Now",
        subtitle: "Three new enforcement actions in Q1 alone.",
        excerpt: "Three new enforcement actions in Q1 alone. Here's what the latest GDPR rulings mean for your list management and consent flows.",
        body: [
            "The EU Data Protection Board's Q1 2026 guidance tightens the definition of 'legitimate interest' as a lawful basis for marketing email in three critical ways. First, the soft opt-in exemption for existing customers now requires active confirmation within 12 months. Second, pre-ticked consent boxes are now explicitly prohibited across all member states. Third, suppression lists must be maintained indefinitely and cannot be pruned.",
            "Three notable enforcement actions have already landed this quarter. A German newsletter publisher was fined €820K for using pre-checked opt-in boxes during event registration. A UK e-commerce brand received a £490K fine for purging suppression lists as part of a 'list hygiene' process. A French SaaS company was sanctioned for claiming legitimate interest on marketing emails to cold prospects who had never interacted with the brand.",
            "For email marketers, the immediate action items are clear: audit every consent touchpoint in your acquisition flows. Replace any pre-checked boxes with explicit opt-in. Implement a rolling 12-month re-consent campaign for your entire list. Treat your suppression list as a permanent legal record, not a housekeeping task.",
            "MailMind's GDPR module handles suppression list maintenance, consent timestamp storage with cryptographic proof of consent, and automated re-consent campaign generation. If you're not using it, navigate to Settings → Compliance to activate it today. The cost of a fine dwarfs the cost of compliance.",
        ],
        authorKey: "legal",
        tags: ["GDPR", "Compliance", "Legal", "EU"],
        color: "from-rose-500 to-pink-600",
        views: "5.4K",
        likes: "317",
    },
    {
        id: "re-engagement-campaigns",
        category: "Strategy",
        readTime: "5 min",
        date: "Jan 30, 2026",
        featured: false,
        title: "Re-Engagement Campaigns: How to Win Back Dormant Subscribers",
        subtitle: "38% can be re-activated with the right 3-email sequence.",
        excerpt: "Most marketers give up on inactive subscribers too early. Our data shows 38% can be re-activated with the right 3-email sequence.",
        body: [
            "Industry guidance often says you should suppress subscribers after 90 days of inactivity. Our data across 340+ customers tells a different story: with the right re-engagement sequence, 38% of subscribers dormant for up to 18 months can be reactivated.",
            "The winning sequence structure: Email 1 is a simple, low-pressure check-in. No offers, no urgency. A single clear question — 'Do you still want to hear from us?' — with a single CTA. This email typically gets a 28% open rate among dormant subscribers because it feels different from every other email they receive. It's honest.",
            "Email 2 goes out on day 4 if there's been no open. Light social proof of what they've missed, framed entirely around value. Not 'look what you ignored' but 'here's what our engaged subscribers have been using'. Real examples, real outcomes.",
            "Email 3 on day 9 presents a clear, respectful choice: stay in or opt out gracefully. The subject line is simply 'Staying or going?' The body is two sentences and two buttons. This email is counterintuitively your highest performer — when someone who thought they were done sees you giving them a clean exit, many re-engage out of genuine interest rekindled by the respectful framing.",
            "After the three-email sequence, anyone who hasn't engaged should be suppressed — but not deleted. Keep them in a suppressed segment for 90 days in case they contact support or make a purchase, which would trigger re-activation. After 90 days of suppression with no activity, they're done.",
        ],
        authorKey: "tyler",
        tags: ["Re-engagement", "Lifecycle", "Strategy", "List Health"],
        color: "from-teal-500 to-emerald-600",
        views: "6.1K",
        likes: "398",
    },
    {
        id: "send-time-science",
        category: "Analytics",
        readTime: "6 min",
        date: "Jan 27, 2026",
        featured: false,
        title: "Send-Time Optimization: The Science Behind Knowing When to Send",
        subtitle: "We analyzed 2.3B sends to identify the patterns.",
        excerpt: "We analyzed 2.3 billion sends to identify the patterns. Peak engagement windows vary wildly by industry, segment, and geography — here's the data.",
        body: [
            "The question every email marketer asks is 'when should I send?' The honest answer is: not at 9am Tuesday. That's just when everyone else sends. Competing in a crowded inbox at the industry's favorite send time is one of the most reliable ways to underperform.",
            "Our analysis of 2.3 billion sends across MailMind's platform reveals four behavioral archetypes: the Early Bird (5–7am, 23% of subscribers, highest in finance and news), the Commuter (7:30–9am on mobile, best for short-form content), the Lunch Breaker (12–1pm, strongest for B2C retail and food), and the Late Night Scroller (9pm–11pm, highest for education and personal development).",
            "These archetypes aren't industry rules — they're individual traits. The same person can be an Early Bird for one newsletter and a Lunch Breaker for another, depending on the mental context they associate with that sender. This is why population-level send-time data is only marginally useful.",
            "What matters is subscriber-level send-time modeling. MailMind tracks each subscriber's open timestamps across their last 60 interactions and builds a probability distribution for each hour of the week. Your next send is timed to the peak of that distribution, per subscriber.",
            "The lift from individualized send-time optimization averages 14–22% across our customer base. For high-frequency senders, it compounds: a 15% lift on Monday becomes a 15% lift on Tuesday, Wednesday, Thursday, Friday. Over a year, that's a meaningful revenue delta from changing nothing but delivery timing.",
        ],
        authorKey: "leo",
        tags: ["Send-Time", "Analytics", "Optimization", "Data"],
        color: "from-purple-500 to-violet-600",
        views: "7.8K",
        likes: "521",
    },
    {
        id: "list-segmentation-masterclass",
        category: "Strategy",
        readTime: "7 min",
        date: "Jan 22, 2026",
        featured: false,
        title: "List Segmentation Masterclass: From Spray-and-Pray to Surgical Precision",
        subtitle: "Segmented campaigns generate 760% more revenue than batch-and-blast.",
        excerpt: "Segmented campaigns generate 760% more revenue than batch-and-blast. Here's the exact taxonomy we use with our highest-performing customers.",
        body: [
            "Segmentation isn't just dividing your list by demographics. The most effective segmentation frameworks combine behavioral signals (what actions they've taken), predictive scores (what they're likely to do next), and lifecycle stage (where they are in their journey with your product).",
            "The five-tier segmentation model we recommend begins with Champions — subscribers who have purchased 3+ times, have high LTV, and open more than 70% of emails. These are your most valuable relationships. Treat them that way: first access, exclusive content, personal outreach.",
            "Loyal Engagers open nearly everything but haven't converted. They're close. The strategy here is social proof and light urgency — not discount codes, which train them to wait. Show them what Champions are getting. Make them feel like they're on the edge of the inner circle.",
            "At-Risk subscribers were once active but are going cold. Engagement Decay Rate is your early warning signal. When a subscriber's 90-day average drops below their historical average by more than 30%, they enter At-Risk status automatically in MailMind. Don't wait until they're fully dormant — intervene with a win-back sequence now.",
            "Price-Sensitive subscribers only convert when there's an offer. They're valuable but require discipline: discount too often and you've trained them to wait permanently. The right strategy is occasional, clearly time-limited offers framed as exceptional events, not your standard operating procedure.",
            "Finally, Dormant subscribers get a structured re-engagement or suppression decision. The goal isn't to keep them at all costs — it's to cleanly resolve the relationship so your list health score improves and your deliverability doesn't suffer from sending to dead addresses.",
        ],
        authorKey: "sophie",
        tags: ["Segmentation", "Strategy", "Targeting", "Lifecycle"],
        color: "from-orange-500 to-amber-600",
        views: "5.9K",
        likes: "374",
    },
]
